# Generated by Django 4.2.7 on 2023-11-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/blog'),
        ),
    ]
